name: Reflexa
options:
  bundleIdPrefix: com.reflexa
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait

targets:
  Reflexa:
    type: application
    platform: iOS
    sources:
      - path: Reflexa
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.reflexa.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: Reflexa
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UILaunchScreen_UIColorName: LaunchBackground
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: true
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Reflexa/Reflexa.entitlements
    dependencies:
      - sdk: AVFoundation.framework
      - sdk: CoreHaptics.framework
